### DISCUSSION TITLE
dbx support for pipelines (delta live tables)

### DISCUSSION THREAD

**Discussion by benbauer89** [databrickslabs/dbx#250] [Ideas]
Hey, I was wondering whether it's already possible to use dbx to deploy pipelines (delta live tables).
If not it would be a great feature :)

**Comment by renardeinside** [comment]
hi @benbauer89 , 
we have plans to support DLT, but currently are constrained from multiple sides.

**Reply by jiri-vinarek** [reply]
I agree it would be a great feature :) @renardeinside what are the main roadblocks? Just curious.

**Reply by guillesd** [reply]
yes, I am also really interested in this feature. Many of my clients are interested in using dbx but also DLTs... it feels like a natural thing that dbx supports pipelines! Can we help somewhere @renardeinside?

**Reply by renardeinside** [reply]
Hi everyone on this thread! 

We're in progress of implementation, most probably DLT support will be delivered until end of first week of October (7-8 approx.)

**Reply by renardeinside** [reply]
implemented in #531 will be soonish released in 0.8.0

**Comment by ctaylor-carvana** [comment]
Amazing! Question, does this support permission setting as well? Just appending these to the pipeline list doesn’t seem to work. I can’t find any example of properly setting the permission. https://docs.databricks.com/workflows/delta-live-tables/delta-live-tables-api-guide.html
access_control_list:
  - user_name: ***@***.***
    permission_level: IS_OWNER
  - group_name: team_ngc
    permission_level: CAN_MANAGE
Best,
 

Christina Taylor
***@***.***

**Reply by renardeinside** [reply]
yes, it definitely does apply the permissions. Please note that they shall be provided on the level of the pipeline definition, e.g.:
```yaml
environments:
  default:
    workflows:
      - name: "[dev][dbx-dlt-test]"
        workflow_type: "pipeline"
        development: true
        libraries:
          - notebook:
              path: "/Repos/some/path"
        clusters:
          - label: "default"
            autoscale:
              min_workers: 1
              max_workers: 3
              mode: "ENHANCED"
            driver_instance_pool_id: "instance-pool://itrusov-pool"
            instance_pool_id: "instance-pool://itrusov-pool"
        access_control_list:
          - user_name: "some@email.com"
            permission_level: "IS_OWNER"
          - group_name: "some-group"
            permission_level: "CAN_VIEW"
```
