### DISCUSSION TITLE
Run databricks jobs for code in merged state

### DISCUSSION THREAD

**Discussion by datascientistlin** [databrickslabs/dbx#416] [Q&A]
Hi Team,

As far as I understood, I could choose from *branch*, *commit* and *tag* if my task source is **GIT**. However, the use case I'm trying to implement is to run the databricks jobs during the PR merging state. This could help us perform integration testing, to ensure the code is running fine after merging the PR (before the actual merging happens).

We used Azure Devops platform for CICD and Repo. Here is how I have implemented it so far.

In *pipelines.yml* file:

```
  - job: On_PR
    displayName: Build on new PR
    condition: eq(variables['Build.Reason'], 'PullRequest')

      steps:
          # Add DEPLOY_COMMIT variable to be used in dbx environment
          - script: |
              echo "##vso[task.setvariable variable=DEPLOY_COMMIT;]$(Build.SourceVersion)"
            displayName: Set DEPLOY_COMMIT variable
          # Deploy databricks job using dbx
          - script: |
              source /usr/share/miniconda/etc/profile.d/conda.sh
              conda activate ${{ parameters.CONDA_ENV }}
              dbx deploy --job=${{ parameters.JOB_NAME }} --files-only --requirements-file requirements.txt
            displayName: Deploy Databricks Job
          # Launch databricks job using dbx
          - script: |
              source /usr/share/miniconda/etc/profile.d/conda.sh
              conda activate ${{ parameters.CONDA_ENV }}
              dbx launch --job=${{ parameters.JOB_NAME }} --as-run-submit --trace 
            displayName: Launch Databricks Job
``` 

In deployment.yml file

```
Environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "Training-Job"
        new_cluster:
          spark_version: "10.4.x-scala2.12"
          num_workers: 1
          node_type_id: "Standard_E16d_v4"
        notebook_task:
          notebook_path: "notebooks/training"
          source: "GIT"
        git_source: 
          git_url: "https://xxx@dev.azure.coml/_git/xxx"
          git_provider: "azureDevOpsServices"
          git_commit: {{ env['DEPLOY_COMMIT'] }}
```

The problem with this implementation is `DEPLOY_COMMIT` does not work in the PR merging state. This is because the commit during PR merging is a synthesized one which could not be checked out in the actual pipeline.

Thanks in advance for any tips and advises.
