### DISCUSSION TITLE
FileNotFoundError when using dynamic parameters functionality in dbx launch

### DISCUSSION THREAD

**Discussion by JensvandeZande** [databrickslabs/dbx#614] [Q&A]
I am having trouble using dynamic parameters and configuration files while using the spark_python_task method. It seems that "dbx launch" does not resolve "file:fuse://" properly. This can be related to this [issue](https://github.com/databrickslabs/dbx/issues/615). Let me sketch the situation.

I am using dbx's Task() abstract base class as described [here](https://dbx.readthedocs.io/en/latest/guides/python/python_quickstart/) for its various functionalities. In particular its configuration file reader methods. I use this configuration file to tell each task where to read and write the data. Next to the "--conf-file" parameter I have another parameter "--date" that I want to use as a dynamic parameter. For this, I used argument parser just like the Task._get_conf_file() method. However, when supplying parameters to the "--parameters" argument of "dbx launch" I need to also provide "--conf-file" parameter as the "parameters" argument in the task definition of the deployment.yml file gets overwritten when supplying dynamic parameters.

My deployment.yml looks like this:
```yml

environments:
  default:
    workflows:
      - name: "bronze2gold"
        job_clusters:
            - job_cluster_key: "my_cluster"
              <<: *basic-static-cluster

        tasks:
          - task_key: "bronze2silver"
            job_cluster_key: "my_cluster"
            spark_python_task:
              python_file: "file://project1/table1/tasks/bronze2silver.py"
              parameters: ["--conf-file", "file:fuse://project1/table1/conf/tasks/bronze2silver.yml"]

          # - task_key: "silver2gold"
          #   depends_on:
          #       - task_key: "bronze2silver"
          #   job_cluster_key: "my_cluster"
          #   spark_python_task:
          #     python_file: "file://project1/table1/tasks/silver2gold.py"
          #     parameters: ["--conf-file", "file:fuse://project1/table1/conf/tasks/silver2gold.yml"]

```

My cli call looks like this:
```bash
dbx deploy bronze2gold --deployment-file project1/table1/conf/deployment.yml
dbx launch bronze2gold --parameters='{"python_params":["--conf-file", "file:fuse://project1/table1/conf/tasks/bronze2silver.yml", "--date", "2022/11/02"]}'
```
I can see in the output that the arguments are being parsed, but I get the error FileNotFoundError: [Errno 2] No such file or directory:  "file:fuse://project1/table1/conf/tasks/bronze2silver.yml". 

I have tried "/dbfs/" and "dbfs://" instead of "file:fuse:" but I get the same error.

When I use "dbx execute" everything works:
```bash
dbx execute bronze2gold --task=bronze2silver--cluster-name="somePersonalCluster" --deployment-file project1/table1/conf/deployment.yml --parameters='{"parameters"["--conf-file", "file:fuse://project1/table1/conf/tasks/bronze2silver.yml", "--date", "2022/28/02"]}'
```

Can anyone explain to me what is happening and how I can solve my problem? Also, how should I solve it when I add a second task to my workflow that has a separate config file? See commented lines in deployment.yml. Per the [documentation](https://dbx.readthedocs.io/en/latest/guides/general/passing_parameters/?h=dynami#dynamic-parameter-passing) it is not possible to provide task specific parameters. Does this then mean we cannot use dbx's Task() abstract base class when using dynamic parameters?

KR Jens
