### DISCUSSION TITLE
File Arrival support

### DISCUSSION THREAD

**Discussion by ghost** [databrickslabs/dbx#753] [Q&A]
Hello, is there any plan to support [File Arrival triggers](https://learn.microsoft.com/en-gb/azure/databricks/workflows/jobs/file-arrival-triggers)? If the feature is already supported, I could not find any relevant documentation on how to define it, would you direct me to it?

**Comment by tv-long** [comment]
@giovannipapini-agilelab 
The job definition follow this API structure, you can find `Trigger` section
https://docs.databricks.com/api/azure/workspace/jobs/create
In my case, I used:
```
      - name: "job-trigger-by-file-arrival"
        trigger:
          pause_status: "UNPAUSED"
          file_arrival:
            url: "abfss://path/to/my/folder"
```
