### DISCUSSION TITLE
Fetch current user info to set workflow owner automatically

### DISCUSSION THREAD

**Discussion by JonasDev1** [databrickslabs/dbx#779] [Ideas]
Hey there,

due to the fact that normal users can't change the workflow owner, we always use the deployment user as the workflow owner. Currently we have multiple deployment users(one for each permission group) and always have to set the owner name manually.

I saw that there is a current [user API endpoint](https://docs.databricks.com/api-explorer/workspace/currentuser/me). With this it's possible to set the owner automatically. I would prefer to use a named property. 
With the new reference-based approach, it would look like this:

```
environments:
  default:
    workflows:
      - name: "example-workflow"
        access_control_list:
         - service_principal_name: "current-user://userName"
           permission_level: "IS_OWNER"
```

What are your thoughts?

**Comment by renardeinside** [comment]
hi @JonasDev1 , 

you can implement this API call and programmatically substitute the user by using the [custom functions.](https://dbx.readthedocs.io/en/latest/features/jinja_support/?h=function#custom-functions-support)

e.g. you add a function to retrieve the current user:
```python
# .dbx/_custom_jinja_functions.py
def retrieve_current_user() -> str:
  ...
```

And then use it inside your `conf/deployment.yml`:

```yml
environments:
  default:
    workflows:
      - name: "example-workflow"
        access_control_list:
         - service_principal_name: {{ custom.retrieve_current_user() }}
           permission_level: "IS_OWNER"
```
