### DISCUSSION TITLE
deploy with tags contains special caracter

### DISCUSSION THREAD

**Discussion by slenain** [databrickslabs/dbx#792] [Q&A]
Hello,

We trying to deploy with dbx deploy tags of project like this :

dbx deploy --environment=PROD --jobs=example-sample --tags url_project='mysiteweb.com/project=example'

And we have pb, project are deployed without error but tags in databricks look like : 
![image](https://github.com/databrickslabs/dbx/assets/8959488/8898ea99-f126-4d09-b605-64cfabe98e41)

Can you help me ?

Thank you

**Comment by renardeinside** [comment]
hi @slenain , 

first of all please don't use discussions - use issues (as it's said in the README.md and docs). 
I don't have any notifications on what's happening here and have had a chance to notice this accidentally. 

you're using the wrong tags. --tags in the CLI command has not relation to the job tags. To provide tags for a job use the following payload in your deployment.yml file:

```yaml

environments:
  development:
    workflows:
      - name: workflow-name
        tags:
          TAG_NAME: 'tag-value'
          ANOTHER_TAG_NAME: 'another tag value'
```
