### ISSUE TITLE
[DISCUSSION] Question about environment variables in yaml deployment file

### ISSUE THREAD

**Issue by pingu1m** [databrickslabs/dbx#101]
## Expected Behavior

On this docs page (https://dbx.readthedocs.io/en/latest/quickstart.html?highlight=env#id2)

There is a note that says: "Unlike JSON, in YAML you have to specify the !ENV tag before your environment variables for it to be resolved in a valid manner."

I have tried to do this on my yaml but it is not working. Could you guys help me out with a working example?

deployment.yaml
```yaml

environments:
  default:
    jobs:

      - name: test1
        <<: *basic-settings
        tasks:
          - task_key: "main-task"
            <<:
              - *basic-settings
              - *basic-autoscale-cluster
            spark_python_task:
              python_file: company/jobs/sample/entrypoint.py
              parameters:
                - "--e"
                - ${!ENV:PWD}
                - "--f"
                - '${!ENV:PATH}'
                - "--g"
                - '${!ENV:PWD}'
                - "--h"
                - '${!ENV:ENVI}'
                - "--i"
                - ${!ENVI}
                - "--j"
                - ${!PWD}
                - "--k"
                - ${!TERM}



```
## Your Environment

* dbx version used: 0.2.1
* Databricks Runtime version:

**Comment by pingu1m** [comment]
Update:
I was able to get it working after debugging the source code.

For anyone that have the same issue here is the working code.

```yaml
environments:
  default:
    jobs:

      - name: test1
        <<: *basic-settings
        tasks:
          - task_key: "main-task"
            <<:
              - *basic-settings
              - *basic-autoscale-cluster
            spark_python_task:
              python_file: reklaim/jobs/sample/entrypoint.py
              parameters:
                - "--e"
                - ${PWD:PWD}
```

As you can see  all it is needed is the   ENV_NAME:DEFAULT_VALUE inside the ${}. Ex: ${ENVIRONMENT:DEVELOPMENT}

Hope it helps someone else.

Is this a documentation problem or an implementation problem? I can push a PR but I need to know what to fix.
