### ISSUE TITLE
Add support for cluster reuse inside of multi-tasks jobs

### ISSUE THREAD

**Issue by rfcortes** [databrickslabs/dbx#164]
## Expected Behavior

A job cluster can be referenced and reused inside a multi-task job.
Feature recently introduced in databricks [here](https://docs.microsoft.com/en-us/azure/databricks/data-engineering/jobs/jobs-api-updates) and [here](https://databricks.com/blog/2022/02/04/saving-time-and-costs-with-cluster-reuse-in-databricks-jobs.html)

## Current Behavior
Job cluster can't be reused

## Your Environment

* dbx version used: 0.2.2
* Databricks Runtime version:

**Comment by rfcortes** [comment]
thanks @renardeinside

**Comment by renardeinside** [comment]
quick question in this regard @rfcortes, 
I've just tested the following setup with 0.3.3 and it works perfectly fine:

```
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "9.1.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "i3.xlarge"

# please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "dbx_jobs_v21_test"
        job_clusters:
          - job_cluster_key: "basic-cluster"
            <<: *basic-static-cluster
        tasks:
          - task_key: "first-task"
            job_cluster_key: "basic-cluster"
            spark_python_task:
              python_file: "file://dbx_jobs_v21/jobs/sample/entrypoint.py"
              parameters: ["--conf-file", "file:fuse://conf/test/sample.yml"]
          - task_key: "second-task"
            job_cluster_key: "basic-cluster"
            spark_python_task:
              python_file: "file://dbx_jobs_v21/jobs/sample/entrypoint.py"
              parameters: ["--conf-file", "file:fuse://conf/test/sample.yml"]
          - task_key: "third-task"
            job_cluster_key: "basic-cluster"
            depends_on:
              - task_key: "first-task"
              - task_key: "second-task"
            spark_python_task:
              python_file: "file://dbx_jobs_v21/jobs/sample/entrypoint.py"
              parameters: ["--conf-file", "file:fuse://conf/test/sample.yml"]
            
```
The only thing I've changed in my setup is the following - to enable support for Jobs API 2.1 I've explicitly set it in the databricks configure:
```
databricks configure \ 
   --profile <> # some existing profile name
   --token # because I don't want to change the token
   -- jobs-api-version 2.1 # this will update the config
```
After it everything works fine with all configurations. Henceforth a question - what cases are not covered here?
