### ISSUE TITLE
[Feature] Include notebook as artifact

### ISSUE THREAD

**Issue by kulmam92** [databrickslabs/dbx#181]
## Expected Behavior
If you have a "notebook_task" job, notebooks in the "notebook_path" to the artifacts.

```
    jobs:
      - name: "EmpAttr-sample"
        <<:
          - *basic-static-cluster
        spark_python_task:
          python_file: "file://empattr/jobs/sample/entrypoint.py"
          parameters: ["--conf-file", "file:fuse://conf/test/sample.yml"]
      - name: "EmpAttr-notebook"
        <<:
          - *basic-static-cluster
        notebook_task:
          notebook_path: "/Shared/empattr/develop_model"
```

## Current Behavior
notebook is not included in the artifacts.

```
.dbx
conf
dist
empattr
tests
```

## Context
It will be great if the files used to create model are included in the artifacts.

## Your Environment
Azure

* dbx version used: 0.4.1
* Databricks Runtime version: 9.1
