### ISSUE TITLE
add support for general purpose cluster deployment

### ISSUE THREAD

**Issue by mrmasterplan** [databrickslabs/dbx#199]
## Expected Behavior
Allow a section in the environment, next to `jobs`, allow a `clusters` key.
Besides a name it would contain details on libraries and configuration for a list of general purpose clusters.
The deployed cluster would also contain an installed build of the current library.

## Current Behavior
General purpose clusters need to be deployed with other command line tools.

## Steps to Reproduce (for bugs)
n/a

## Context
Besides ETL jobs, we provide a general purpose cluster in our databricks environment with a number of configurations and tooling available in a python wheel. The wheel is built and deployed with the general purpose cluster as part of our CI/CD pipeline. We use `dbx` for jobs but wouldn't it be nice to also use `dbx` for the general purpose clusters? We have implemented our oun logic very similar to `dbx` to build and upload our wheel and install it to the general purpose cluster.

## Your Environment

* dbx version used: 0.4.1

* Databricks Runtime version: 9.1

**Comment by renardeinside** [comment]
hi @mrmasterplan , 
thanks for raising the issue.
cluster creation operations are covered by the main databricks CLI. dbx is a tool for jobs deployment, not for cluster management. However, you can provide existing_cluster_id or existing_cluster_name in the deployment file. 

Could you please describe what's the purpose of extending the dbx in this direction? I'm trying to grasp the additional value.

**Comment by renardeinside** [comment]
I see the argument, but I don't get the following - how would be `dbx clusters create` be different from `databricks clusters create`? What is missing in the main CLI that we can improve?

**Comment by mrmasterplan** [comment]
A command to `databricks clusters create` does not modify any of the settings in the json configuration. It is a thin wrapper around the api. There is no upload happening behind the scenes.

What I would like to happen is this:
`deploy.yml`:

```
environments:
  default:
    strict_path_adjustment_policy: true
    clusters:
      - cluster_name: Science Cluster
        spark_version: ...
        ...
        ...
        libraries:
          - maven: 
              coordinates: com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha
    jobs:
      - name: My ETL
        ...
        libraries:
          - maven: 
              coordinates: com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha
   
```

Notice the lack of a python library in the cluster libraries section of both the job and cluster definitions.
I then want to call `dbx deploy`.
This will automatically build, upload and add the library to the job configuration as per today. 
The job configuration will contain the following json snippet:

```
"libraries": [
            {
                "maven": {
                    "coordinates": "com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha"
                }
            },
            {
                "whl": "dbfs:/dbx/my-library/2e22ad635a184cd2af2ce5ca012a21c2/artifacts/dist/my-library-1.0.0-py3-none-any.whl"
            }
        ],
```


I want it to do the same with the general purpose cluster.
