### ISSUE TITLE
Invalid `null` element in list of libraries

### ISSUE THREAD

**Issue by giovannipapini-agilelab** [databrickslabs/dbx#226]
## Current Behavior

When I deploy a 'spark_jar' job on Azure Data Factory, the deploy seems to end correctly but when I then go opening the ADF Pipeline, Azure forces me to manually fix it, since there is a `null` element at the end of the spark_jar list. The element is obviously missing in the DBX deployment yaml, so it could have been added by DBX itself, since it is present in the intermediate 'deployment-result.json'. It keeps the same behaviour when adding more then 1 jar libraries, and it does not when I omit libraries list (but it is then invalid for the missing jar file).

## Context

- adf-databricks-job.yaml:
```
environments:
  dev:
    jobs:
      - name: "test-adf-dev"
        permissions: &permissions
          access_control_list:
            - user_name: [omissis]
              permission_level: IS_OWNER
            - group_name: [omissis]
              permission_level: CAN_MANAGE
        new_cluster: &new-cluster-spec
          num_workers: 1
          policy_name: default_job_cluster
        parameters: &parameters [ ]
        max_retries: 0
        libraries: &libraries
          - jar: target/scala-2.12/test-adf_2.12-20220506T083827.jar
        spark_jar_task:
          main_class_name: [omissis]
      - name: "test-adf-dev-step2"
        permissions: *permissions
        new_cluster: *new-cluster-spec
        parameters: *parameters
        max_retries: 0
        libraries: *libraries
        spark_jar_task:
          main_class_name: [omissis]
```
- deploy command:
```
dbx deploy --no-rebuild --environment='dev' --deployment-file='adf-databricks-job.json' --write-specs-to-file='.dbx/deployment-result.json' --files-only
```
- deployment-result.json
```
{
    "dev": {
        "jobs": [
            {
                "name": "test-adf-dev",
                "permissions": {
                    "access_control_list": [
                        {
                            "user_name": "[omissis]",
                            "permission_level": "IS_OWNER"
                        },
                        {
                            "group_name": "[omissis]",
                            "permission_level": "CAN_MANAGE"
                        }
                    ]
                },
                "new_cluster": {
                    "num_workers": 1,
                    "policy_name": "default_job_cluster",
                    "instance_pool_id": "[omissis]",
                    "spark_version": "10.4.x-scala2.12",
                    "cluster_log_conf": {
                        "path": "[omissis]"
                    },
                    "policy_id": "[omissis]"
                },
                "parameters": [],
                "max_retries": 0,
                "libraries": [
                    {
                        "jar": "target/scala-2.12/test-adf_2.12-20220506T083827.jar"
                    },
                    null
                ],
                "spark_jar_task": {
                    "main_class_name": "[omissis]"
                }
            },
            {
                "name": "test-adf-dev-step2",
                "permissions": {
                    "access_control_list": [
                        {
                            "user_name": "[omissis]",
                            "permission_level": "IS_OWNER"
                        },
                        {
                            "group_name": "[omissis]",
                            "permission_level": "CAN_MANAGE"
                        }
                    ]
                },
                "new_cluster": {
                    "num_workers": 1,
                    "policy_name": "default_job_cluster",
                    "instance_pool_id": "[omissis]",
                    "spark_version": "10.4.x-scala2.12",
                    "cluster_log_conf": {
                        "path": "[omissis]"
                    },
                    "policy_id": "[omissis]"
                },
                "parameters": [],
                "max_retries": 0,
                "libraries": [
                    {
                        "jar": "target/scala-2.12/test-adf_2.12-20220506T083827.jar"
                    },
                    null
                ],
                "spark_jar_task": {
                    "main_class_name": "[omissis]"
                }
            }
        ]
    }
}
```
- data factory reflect command
```
dbx datafactory reflect \
  --specs-file='.dbx/deployment-result.json' \
  --subscription-name='[omissis]' \
  --resource-group='[omissis]' \
  --factory-name='[omissis]' \
  --name='[omissis]' \
  --environment='dev'
```

## Your Environment

```
❯ python --version
Python 3.9.7
❯ databricks --version
Version 0.16.4
❯ dbx --version
DataBricks eXtensions aka dbx, version ~> 0.4.1
```
