### ISSUE TITLE
dbx execute on interactive cluster throws and error

### ISSUE THREAD

**Issue by VenkatH** [databrickslabs/dbx#249]
## Current Behavior

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/15984917/169148851-dab8da11-0243-4437-a1b7-e93b4d2e0aac.png">

## Steps to Reproduce (for bugs)
- pycharm 
   - 3.8.10 pipenv  as local interpreter 
   -  dbx runs along with databricks-cli on conda env 
   - followed all the docs steps
- Intellij
   - 3.8.10 conda python env
    -  dbx runs along with databricks-cli on conda env 
   - followed all the docs steps

## Context

Able to reproduce the issue in both PyCharm and also Intellij

## Your Environment

* dbx version used: 0.4.1
* Databricks Runtime version: 10.5 ML

**Comment by renardeinside** [comment]
hi @VenkatH ,
thanks a lot for raising the issue. Could you please provide your deployment configuration? Please don't forget to remove parts that are specific to your environment.

**Comment by VenkatH** [comment]
@renardeinside  you mean deployment.yaml file content. if so here it is 
```
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "dbx-demo-job"
        spark_python_task:
          python_file:  "dbx-demo-job.py"%     
```

But I made it work by verifying the basic python template code. The databricks docs didn't mention to create wheel package, it fixed the issue.
