### ISSUE TITLE
[Feature] Support job DAGs

### ISSUE THREAD

**Issue by dcaribou** [databrickslabs/dbx#294]
## Context
As the number and complexity of jobs in a dbx project, one typical requirement is the possibility to encode job dependencies in a DAG. This allows users to do things like running portions of the DAG (like in "run this job and all their dependant jobs") or rendering documentation for a project's job hierarchy.

```yaml
environments:
  default:
    jobs:
      - name: "your-job-name"
        <<: *basic-static-cluster
        libraries: []
        max_retries: 0
        spark_python_task:
          python_file: "file://tests/deployment-configs/placeholder_1.py"
       depends_on:
         - your-job-name-2
         
      - name: "your-job-name-2"
        <<: *basic-static-cluster
        libraries: []
        max_retries: 0
        spark_python_task:
          python_file: "file://tests/deployment-configs/placeholder_2.py"
```

```shell
# this would run first your-job-name-2 and second your-job-name
dbx execute --job=your-job-name --with-dependencies 
```

To the best of my knowledge, this feature does not currently exist in dbx. I wonder if this functionality lays within the vision of what dbx what's to support at some point in time.
