### ISSUE TITLE
Unable to see job after running dbx execute

### ISSUE THREAD

**Issue by knjk04** [databrickslabs/dbx#299]
## Expected Behavior

See the job run in the Databricks UI.

## Current Behavior

I get the message `Command successfully executed`, but I am unable to see the job in the Databricks UI.

## Steps to Reproduce (for bugs)
1. Initialise the project using the Python template: `dbx init --template=python_basic`

2. Update the deployment configuration:
```yaml
# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "9.1.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "i3.xlarge"

# please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      ##################################################################
      # this is an example job with single ETL task based on 2.0 API  #
      #################################################################
      - name: "dbx-demo-sample-etl-2.0"
        <<: *basic-static-cluster
        spark_python_task:
          python_file: "file://dbx_demo/workloads/sample_etl_job.py"
          parameters: ["--conf-file", "file:fuse://conf/test/sample_etl_config.yml"]
```

3. Run `dbx execute --job=dbx-demo-sample-etl-2.0 --cluster-name=git-proxy --deployment-file=conf/simple-deployment.yml` (I renamed my config):
```
[dbx][2022-06-23 10:57:41.777] No environment variables provided, using the ~/.databrickscfg
[dbx][2022-06-23 10:57:43.856] Executing job: dbx-demo-sample-etl-2.0 in environment default on cluster git-proxy (id: 0516-145600-2xwplki1)
[dbx][2022-06-23 10:57:43.856] Re-building package
/Users/karankumar/.virtualenvs/dbx/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
[dbx][2022-06-23 10:57:45.463] Package re-build finished
[dbx][2022-06-23 10:57:45.463] Using the provided deployment file conf/simple-deployment.yml
[dbx][2022-06-23 10:57:45.468] Preparing interactive cluster to accept jobs
[dbx][2022-06-23 10:57:45.490] Cluster is ready
[dbx][2022-06-23 10:57:45.491] Preparing execution context
[dbx][2022-06-23 10:57:45.732] Existing context is active, using it
[dbx][2022-06-23 10:57:45.968] Uploading file: requirements.txt
[dbx][2022-06-23 10:57:46.673] Installing provided requirements
[dbx][2022-06-23 10:57:58.238] Provided requirements installed
[dbx][2022-06-23 10:57:58.239] Locating package file
[dbx][2022-06-23 10:57:58.240] Package file located in: dist/dbx_demo-0.0.1-py3-none-any.whl
[dbx][2022-06-23 10:57:58.240] Uploading file: dist/dbx_demo-0.0.1-py3-none-any.whl
[dbx][2022-06-23 10:57:58.939] Installing package
[dbx][2022-06-23 10:58:04.692] Package installation finished
[dbx][2022-06-23 10:58:04.780] Processing parameters
[dbx][2022-06-23 10:58:04.780] Uploading file: conf/test/sample_etl_config.yml
[dbx][2022-06-23 10:58:05.512] Processing parameters - done
[dbx][2022-06-23 10:58:05.512] Starting entrypoint file execution
[dbx][2022-06-23 10:58:16.778] Command successfully executed

[dbx][2022-06-23 10:58:16.778] Command execution finished
```

## Context

I am looking to run the demo sample ETL job that is in the Python template.

## Your Environment

* dbx version used: 0.5.0
* Databricks Runtime version: 0.16.6
