### ISSUE TITLE
`--branch-name` as environment variable for `git_source`

### ISSUE THREAD

**Issue by mickvanhulst-TomTom** [databrickslabs/dbx#353]
## Expected Behavior
Whenever `--branch-name` is passed as an argument, it would be useful if the branch name is accessible for setting the `git_branch` for a given job. Currently, it does not seem to be accessible as an environment variable. 

## Current Behavior
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
Dynamically changing the branch name would improve the development experience, which in turn would seamlessly integrate with CI/CD. An alternative is using Jinja2 variable files. Note that if there are any other alternatives, then I would welcome any suggestions :)! 

## Your Environment
N/A

* dbx version used: 0.6.8
* Databricks Runtime version: 10.4

**Comment by renardeinside** [comment]
hi @mickvanhulst-TomTom , 
you can use the env variable in the following fashion:
```
BRANCH_NAME=<set-your-branch-name> # setup the env variable
```
In your deployment file, use Jinja2 template capabilities with [env variable support ](https://dbx.readthedocs.io/en/latest/features/jinja2_support.html#environment-variables):
```
# conf/deployment.yml.j2
      git_source:
        git_url: https://some-git-provider.com/some/remote/repo.git
        git_provider: "git-provider-name"
        git_branch: env["BRANCH_NAME"]
```
re-use this variable in dbx deploy and launch:
```
dbx deploy --branch-name=$BRANCH_NAME
dbx launch --branch-name=$BRANCH_NAME
```
Please note that branch-name argument here is only used by dbx to define which deployment definition (stored remotely) shall be used.
