### ISSUE TITLE
Jinja variables not working

### ISSUE THREAD

**Issue by ptabandzelic** [databrickslabs/dbx#374]
Hi, so i have a jinja_vars.yml where i specified TAG: "0.0.1".Then inside deployment.yml.j2 i reference to it as {{ var['TAG'] }}.But in databricks UI it says null. When i export TAG=0.0.1 and reference it in configuration of deployment by {{ env['TAG'] }}.It works.
I mean i tried everything it wont use jinja-variables-file.Its latest version of dbx.

**Comment by ptabandzelic** [comment]
Also can i use include with yaml or only json?Would appreciate examples.

**Comment by renardeinside** [comment]
hi @ptabandzelic , 
Could you please provide your deployment file (you can delete the private information parts from it), as well as the command you're using (e.g. dbx deploy) with all arguments.

**Comment by ptabandzelic** [comment]
```
custom:
  cluster-props: &cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"
    node_type_id: "m4.large"
    driver_node_id: "m4.large"
    creator_user_name: "" 
  
  autoscale-props: &autoscale-props
    autoscale:
      min_workers: 1
      max_workers: 2
      
    aws-props: &aws-props
      aws_attributes:
        availability: "SPOT"
        ebs_volume_type: "GENERAL_PURPOSE_SSD"
        ebs_volume_count: 1
        ebs_volume_size: 75
    ```
  autoscale-cluster: &autoscale-cluster
    new_cluster:
      <<: 
        - *cluster-props
        - *autoscale-props
        - *aws-props

environments:
  production:
    jobs:
      - name: "test-integration-test"
        job_clusters:
          - job_cluster_key: ""
            <<: *autoscale-cluster
        tags:
          version:  {{ var["TAG"] }}
          
        email_notifications:
          on_start: [  ]
          on_success: [  ]
          on_failure: [ ]
        
        tasks:
          - task_key: "integration_test"
            description: |
              "Integration test for our usecase."
            job_cluster_key: ""
            
            max_retries: {{ var["TASK_RETRIES"] }}
            min_retry_interval_millis: {{ var["RETRY_INTERVAL"] }}
            retry_on_timeout: {{ var["RETRY_TIMEOUT"] }}
