### ISSUE TITLE
How to configure access_control_list with Job API 2.1?

### ISSUE THREAD

**Issue by tonkolviktor** [databrickslabs/dbx#384]
## Expected Behavior
First run: My user is added as owner and the additional groups show up in the UI.
Subsequent runs: if access_control_list changes in yaml its reflected in the UI.

## Current Behavior
First run: my user is added as owner and the additional groups do not show up in the UI.
Subsequent runs: if access_control_list changes in yaml nothing happens in the UI.

## Steps to Reproduce (for bugs)
- `touch placeholder_2.py`
- `touch placeholder_2.py`
- `touch requirements-empty.txt`
- create dbx_access.yaml:
```
# http://yaml.org/spec/1.2/spec.html
# https://learnxinyminutes.com/docs/yaml/

custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"
    node_type_id: "Standard_DS3_v2"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 2

environments:
  default:
    jobs:
      - name: "DBX-ACCESS-TEST"
        access_control_list:
          - group_name: my-existing-group1
            permission_level: CAN_MANAGE
          - group_name: my-existing-group2
            permission_level: CAN_MANAGE
        tasks:
          - task_key: "first-task"
            <<: *basic-static-cluster
            spark_python_task:
              python_file: "file://placeholder_1.py"
          - task_key: "second-task"
            <<: *basic-static-cluster
            spark_python_task:
              python_file: "file://placeholder_2.py"
            depends_on:
              - task_key: "first-task"
```
- run `DATABRICKS_JOBS_API_VERSION=2.1 ./virtualenv/bin/dbx deploy --deployment-file dbx_access.yaml --requirements-file requirements-empty.txt --no-package --write-specs-to-file deployment.json`

- result: (note missing groups)
![image](https://user-images.githubusercontent.com/4534324/184356862-4c6d28f1-2bc2-484f-a116-7cd5730cbaff.png)

## Context
?
How does the correct configuration look like? Thanks.

## Your Environment

- cat ~/.databrickscfg 
```
[DEFAULT]                                                 
host = https://adb-xxxxx.azuredatabricks.net/
token = xxxxx              
jobs-api-version = 2.1   
```
- ./virtualenv/bin/dbx --version
DataBricks eXtensions aka dbx, version ~> 0.6.11
- ./virtualenv/bin/databricks --version
Version 0.17.1

**Comment by tonkolviktor** [comment]
if I change CAN_MANAGE to CanManage it still does not work (for me?).
https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate

**Comment by renardeinside** [comment]
hi @tonkolviktor , 

Thanks a lot for raising the issue, it's a good catch.
RCA:
- On the first job creation the `access_control_list` is supported in the Jobs API 2.1 - as per this [doc](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate). 
- However on repetative call to the Jobs API 2.1 (it will be JobReset) it's not supported as you can see [here](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsReset). 

Resolution:
This is something we shall  cover in the upcoming release of dbx. 

Temporary resolution:
As of now, please feel free to use the standard 2.0 permission [management](https://dbx.readthedocs.io/en/latest/features/permissions.html#job-permissions-management):

```
environments:
  default:
    jobs:
      - name: "DBX-ACCESS-TEST"
        permissions: # note the sub-level here
          access_control_list:
            - group_name: my-existing-group1
              permission_level: CAN_MANAGE
            - group_name: my-existing-group2
              permission_level: CAN_MANAGE
        tasks:
          - task_key: "first-task"
            <<: *basic-static-cluster
            spark_python_task:
              python_file: "file://placeholder_1.py"
          - task_key: "second-task"
            <<: *basic-static-cluster
            spark_python_task:
              python_file: "file://placeholder_2.py"
            depends_on:
              - task_key: "first-task"

```

Your job will still be deployed with all features of 2.1, and then dbx will automatically use the Permissions API to setup the permissions.
