### ISSUE TITLE
'NoneType' object has no attribute 'context_id'

### ISSUE THREAD

**Issue by DanMan259** [databrickslabs/dbx#442]
## Context
Trying to run `dbx execute` and I get an error retrieving a `context_id`. Not sure if I am missing a step or something. For the most part, trying to run a poetry environment remotely. Trying to get a workflow setup using a local ide and remote execution.

Output:
```
│ ╭────────────────────────────────────── locals ───────────────────────────────────────╮          │
│ │ cluster_id = '0810-175714-de06hxy6'                                                 │          │
│ │   language = 'python'                                                               │          │
│ │       self = <dbx.api.context.LowLevelExecutionContextClient object at 0x14e856730> │          │
│ │  v2_client = <databricks_cli.sdk.api_client.ApiClient object at 0x14b059d00>        │          │
│ ╰─────────────────────────────────────────────────────────────────────────────────────╯          │
│                                                                                                  │
│ /Users/dmaniar/processing/.venv/lib/python3.9/site-packages/dbx/api/context.py │
│ :98 in __get_context_id                                                                          │
│                                                                                                  │
│    95 │   │   dbx_echo("Preparing execution context")                                            │
│    96 │   │   ctx = LocalContextManager.get_context()                                            │
│    97 │   │                                                                                      │
│ ❱  98 │   │   if self.__is_context_available(ctx.context_id):                                    │
│    99 │   │   │   dbx_echo("Existing context is active, using it")                               │
│   100 │   │   │   return ctx.context_id                                                          │
│   101 │   │   else:                                                                              │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ──────────────────────────────────────╮            │
│ │      ctx = None                                                                   │            │
│ │ language = 'python'                                                               │            │
│ │     self = <dbx.api.context.LowLevelExecutionContextClient object at 0x14e856730> │            │
│ ╰───────────────────────────────────────────────────────────────────────────────────╯            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'context_id'

```

## Your Environment
macOS Monterey 12.5.1
Apple M1 Chip
Poetry environment with Python 3.9.12

`deployment.yml`:

```
environments:
  default:
    jobs:
      ##################################################################
      # this is an example job with single ETL task based on 2.0 API  #
      #################################################################
      - name: "dev-testing"
        existing_cluster_id: "0110-134714-js06hxy6"
        spark_python_task:
          python_file: "file://common/jobs/entrypoint.py"
          parameters: [
              "--org",
              "cdw"
          ]
```

* dbx version used: 0.7.0
* Databricks Runtime version: 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)
