### ISSUE TITLE
dbx execute command fails for minimal dbx python project on PyCharm

### ISSUE THREAD

**Issue by HimanshuAroraDb** [databrickslabs/dbx#450]
## Expected Behavior
 Command **dbx execute --cluster-id=0114-122447-foods609 himanshu-dbx-demo-job** should deploy and run the pyspark job on an existed interactive cluster.
### Scenario1 
**deployment.yaml** 
```
build:
  no_build: false
environments:
  default:
    workflows:
      - name: "himanshu-dbx-demo-job"
        spark_python_task:
          python_file: "file://dbx-demo-job.py"
```
The dbx execute command is failing with the following error: **_FileNotFoundError: Project package was not found. Please check that /dist directory exists._**

### Scenario2
**deployment.yaml** 
```
#build:
  #no_build: false
environments:
  default:
    workflows:
      - name: "himanshu-dbx-demo-job"
        spark_python_task:
          python_file: "file://dbx-demo-job.py"
```
he dbx execute command is failing with the following error: **_CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8', '-m', 'pip', 'wheel', '-w', 'dist', '-e', '.', '--prefer-binary', '--no-deps']' returned non-zero exit status 1._**

## Steps to Reproduce (for bugs)
1. Create a pycham project as explained in the [doc](https://docs.databricks.com/dev-tools/dbx.html?searchString=&from=0&sortby=_score&orderBy=desc&pageNo=1&aggregations=%5B%5D&uid=7dc8d13f-90bb-11e9-98a5-06d762ad9a62&resultsPerPage=10&exactPhrase=&withOneOrMore=&withoutTheWords=&pageSize=10&language=en&state=1&suCaseCreate=false#pycharm) 
2. Create a minimal dbx project for Python as explained in [doc](https://docs.databricks.com/dev-tools/dbx.html?searchString=&from=0&sortby=_score&orderBy=desc&pageNo=1&aggregations=%5B%5D&uid=7dc8d13f-90bb-11e9-98a5-06d762ad9a62&resultsPerPage=10&exactPhrase=&withOneOrMore=&withoutTheWords=&pageSize=10&language=en&state=1&suCaseCreate=false#create-a-minimal-dbx-project-for-python)
3. Create **dbx-demo-job.py** file on the root folder of project and add the code available in [doc](https://docs.databricks.com/dev-tools/dbx.html?searchString=&from=0&sortby=_score&orderBy=desc&pageNo=1&aggregations=%5B%5D&uid=7dc8d13f-90bb-11e9-98a5-06d762ad9a62&resultsPerPage=10&exactPhrase=&withOneOrMore=&withoutTheWords=&pageSize=10&language=en&state=1&suCaseCreate=false#code-example)
4. Run the following command
`dbx execute --cluster-id=<exitsing-interactive-cluster-id> himanshu-dbx-demo-job`
## Context
**Project structure in Pycharm**
![Screenshot 2022-09-01 at 14 26 35](https://user-images.githubusercontent.com/62250465/187913396-19c3e2fe-fa88-49c0-93c6-8b5ac3238b68.png)
**dbx project.json file**
![Screenshot 2022-09-01 at 14 27 43](https://user-images.githubusercontent.com/62250465/187913601-d341a72a-dd38-43a0-be99-83027ce92b8e.png)
**PipFile**
![Screenshot 2022-09-01 at 14 28 27](https://user-images.githubusercontent.com/62250465/187913721-8e59eca0-7fa5-4f60-949e-eca376e43591.png)

## Your Environment
* dbx version used: 0.7.4
* Databricks Runtime version: 10.4 LTS ML (includes Apache Spark 3.2.1, Scala 2.12)
* python: 3.8
