### ISSUE TITLE
[DOCS] Documentation of "format" key in workflow definition (deployment.yml)

### ISSUE THREAD

**Issue by NodeJSmith** [databrickslabs/dbx#453]
In the latest version of the docs, the [deployment file](https://dbx.readthedocs.io/en/latest/reference/deployment/) page has the below section.

```yaml
        tags:
          your-key: "your-value"
          your-key1: "your-value1"

        format: MULTI_TASK

        permissions:
          access_control_list:
            - user_name: "user@email.com"
              permission_level: "IS_OWNER"
```

With no explanation at all as to what the `format` key is doing, if it's required, or what the other options are for. I've searched for the term "MULTI_TASK" on this repo and found nothing except the commit introducing this change. Is there any information on this?
