### ISSUE TITLE
[FEATURE] Render file provided by --jinja-variables-file in Jinja before loading with YAML

### ISSUE THREAD

**Issue by NodeJSmith** [databrickslabs/dbx#457]
## Desired Behavior
This request is to allow Jinja logic to be usable in the conf/vars.yml file.

The ability to pass a `--jinja-variables-file` argument is a great addition, but many of the variables used on my team are based on the environment. What we would love to do is this:

conf/vars.yml
```yaml
{%- if STG == '0' -%}
job_name: "prod-job-name"
{% else %}
job_name: "stg-job-name"
{% endif %}
```

conf/deployment.yml.j2
```yaml
workflows:
  name: {{ var["job_name"] }}
```

## Current Behavior
In the current setup we would have to define variables in conf/vars.yml like the below, and then still use jinja logic in deployment.yml.j2, which makes the new functionality less useful for our needs.

conf/vars.yml
```yaml
job_name_prod: prod-job-name
job_name_stage: stage-job-name
```

conf/deployment.yml.j2
```yaml
workflows:
{%- if STG == '0' -%}
  name: {{ var["job_name_prod"] }}
{% else %}
  name: {{ var["job_name_stage"] }}
```
