### ISSUE TITLE
Add named property support for service principals

### ISSUE THREAD

**Issue by renardeinside** [databrickslabs/dbx#515]
## Expected Behavior

Would be great to have the same name property support as described [here](https://dbx.readthedocs.io/en/latest/features/named_properties/) for service principals.

 E.g. current state (where XXX-YYY-ZZZ is an id):
 
 ```yml
environments:
  default:
    workflows:
      - name: "uc-job-deployment-sample-etl"
        access_control_list:
          - service_principal_name: "XXX-YYY-ZZZ"
            permission_level: "IS_OWNER"
        tasks:
          - task_key: "main"
            <<: *basic-static-cluster
            python_wheel_task:
              package_name: "uc_job_deployment"
              entry_point: "etl" # take a look at the setup.py entry_points section for details on how to define an entrypoint
              parameters: ["--conf-file", "file:fuse://conf/tasks/sample_etl_config.yml"]
 ``` 
 
 Instead, the following could be introduced:
 
 
  ```yml
environments:
  default:
    workflows:
      - name: "uc-job-deployment-sample-etl"
        access_control_list:
          - service_principal_name: "service-principal://some-nice-name"
            permission_level: "IS_OWNER"
        tasks:
          - task_key: "main"
            <<: *basic-static-cluster
            python_wheel_task:
              package_name: "uc_job_deployment"
              entry_point: "etl" # take a look at the setup.py entry_points section for details on how to define an entrypoint
              parameters: ["--conf-file", "file:fuse://conf/tasks/sample_etl_config.yml"]
 ```
