### ISSUE TITLE
Switch to prefix-based named properties

### ISSUE THREAD

**Issue by renardeinside** [databrickslabs/dbx#516]
## Expected Behavior
Current [named property](https://dbx.readthedocs.io/en/latest/features/named_properties/) passing interface adds accidental complexity and looks awful from design perspective. Instead, we could use prefix-based identification which also would look nice and consistent with `file://` prefixes. 

## Current Behavior

```yml

custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "Standard_E8_v3"
      driver_instance_pool_name: "some-name"
      instance_pool_name: "some-name"
      aws_attributes:
         instance_profile_name: "some-profile-name"
```

## New behaviour

```yml

custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      node_type_id: "Standard_E8_v3"
      driver_instance_pool_id: "instance-pool://some-name"
      instance_pool_id: "instance-pool://some-name"
      aws_attributes:
         instance_profile_arn: "instance-profile://some-instance-profile-name"
```

Old references should trigger a warning that they're deprecated.
