### ISSUE TITLE
`file:` and `file:fuse` not resolved on tasks referencing job_cluster_key

### ISSUE THREAD

**Issue by roelschr** [databrickslabs/dbx#520]
## Expected Behavior
`file:` and `file:fuse:` is resolved for cluster properties on multi-task workflows.

## Current Behavior
I have a multitask workflow (with a deployment file very similar to the one [available in the docs](https://dbx.readthedocs.io/en/latest/reference/deployment/#configuring-complex-deployments)). The major difference is that I have an init_script (and an environment variable) pointing to a file that should be uploaded using the fuse feature.

I suspect that because the API allows for tasks to reference a `job_cluster_key` (for clusters defined in the `workflow[n].job_clusters` parameter), the cluster reference is not being added to the `adjustable_references` here:

https://github.com/databrickslabs/dbx/blob/v0.7.6/dbx/utils/adjuster.py#L33

Causing it to not run the path adjustment callback for job clusters in this workflow.

## Steps to Reproduce (for bugs)
Any multi-task job with cluster definition containing `file:` or `file:fuse` references. Example from docs:

```yaml
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "your-spark-version"
    node_type_id: "your-node-type-id"
    spark_conf:
      spark.databricks.delta.preview.enabled: 'true'
    instance_pool_name: <enter pool name>
    driver_instance_pool_name: <enter pool name>
    runtime_engine: STANDARD
    init_scripts:
      # changed this path
      - dbfs:
        destination: file:fuse://<enter your path>

  basic-auto-scale-props: &basic-auto-scale-props
    autoscale:
    min_workers: 2
    max_workers: 4

  basic-static-cluster: &basic-static-cluster
    new_cluster:
    <<: *basic-cluster-props
    num_workers: 2

  basic-autoscale-cluster: &basic-autoscale-cluster
    new_cluster:
    <<: # merge these two maps and place them here.
      - *basic-cluster-props
      - *basic-auto-scale-props

environments:
  default:
    workflows:
      - name: "your-job-name"

        email_notifications:
          on_start: [ "user@email.com" ]
          on_success: [ "user@email.com" ]
          on_failure: [ "user@email.com" ]
          no_alert_for_skipped_runs: false

        schedule:
           quartz_cron_expression: "00 25 03 * * ?" #
           timezone_id: "UTC"
           pause_status: "PAUSED"

        tags:
          your-key: "your-value"
          your-key1: "your-value1"

        format: MULTI_TASK #

        permissions:
          access_control_list:
            - user_name: "user@email.com"
              permission_level: "IS_OWNER"
            #- group_name: "your-group-name"
            #permission_level: "CAN_VIEW"
            #- user_name: "user2@databricks.com"
            #permission_level: "CAN_VIEW"
            #- user_name: "user3@databricks.com"
            #permission_level: "CAN_VIEW"

        job_clusters:
          - job_cluster_key: "basic-cluster"
              <<: *basic-static-cluster
          - job_cluster_key: "basic-autoscale-cluster"
              <<: *basic-autoscale-cluster

        tasks:
          - task_key: "your-task-01"
            job_cluster_key: "basic-cluster"
            max_retries: 1
            spark_python_task:
              python_file: "file://sample_project/jobs/your-file-01.py"

            min_retry_interval_millis: 900000
            retry_on_timeout: false
            timeout_seconds: 0
            email_notifications:
              on_start:
                - user@email.com
              on_success:
                - user@email.com
              on_failure:
                - user1@email.com
                - user2@email.com

          - task_key: "your-task-02"
            job_cluster_key: "basic-cluster"
            spark_python_task:
              python_file: "file://sample_project/jobs/your-file-02.py"
            depends_on:
              - task_key: "your-task-01"

          - task_key: "your-task-02"
            job_cluster_key: "basic-cluster"
            notebook_task:
              notebook_path: "/Repos/some/project/notebook"
            depends_on:
              - task_key: "your-task-01"
```

* dbx version used: 0.7.6
* Databricks Runtime version: 10.4 

### Quick fix

To make it work for me, instead of using `job_cluster_key`, I'm using a `new_cluster` definition for every task. Unfortunately, that means databricks won't reuse the same cluster across tasks.

Doesn't resolve `file:fuse:`:
```yaml
       ...
        tasks:
          - task_key: "your-task-01"
            job_cluster_key: "basic-cluster"
            max_retries: 1
            spark_python_task:
              python_file: "file://sample_project/jobs/your-file-01.py"
        ...
```

Resolves `file:fuse:`: 
```yaml
       ...
        tasks:
          - task_key: "your-task-01"
            << *basic-static-cluster
            max_retries: 1
            spark_python_task:
              python_file: "file://sample_project/jobs/your-file-01.py"
        ...
```
