### ISSUE TITLE
Job succeeds when pytest fails using cookiecutter entrypoint.py

### ISSUE THREAD

**Issue by jckegelman** [databrickslabs/dbx#524]
## Expected Behavior
Databricks job to fail when pytest fails

## Current Behavior
Databricks job succeeds when pytest fails

## Steps to Reproduce (for bugs)
`tests/integration/test_foo.py`:
```python
def test_foo():
    assert 0
```

`conf/deployment.yml`:
```yaml
environments:
  default:
    workflows:
      - name: "my-integration-tests"
        tasks:
          - task_key: "main"
            <<: *basic-static-cluster
            libraries:
              - pypi:
                  package: "pytest"
            spark_python_task:
              python_file: "file://tests/entrypoint.py"
              parameters: [ "file:fuse://tests/integration" ]
```

```sh
$ dbx deploy my-integration-tests
$ dbx launch my-integration-tests
```

## Context
I believe the cookiecutter template is ignoring `pytest`'s exit code, probably just needs `sys.exit(pytest.main(...))`?

https://github.com/databrickslabs/dbx/blob/99d6126de691af24701a62fffb03d982bb9b5b9f/dbx/templates/projects/python_basic/render/%7B%7Bcookiecutter.project_name%7D%7D/tests/entrypoint.py#L6

## Your Environment

* dbx version used: 0.7.6
* Databricks Runtime version: 10.4 LTS
