### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by aviadshimoni** [databrickslabs/dbx#546]
## Expected Behavior
Deploy a databricks workflow on a new created cluster using service principal
## Current Behavior
RuntimeError: dictionary changed size during iteration
## Steps to Reproduce (for bugs)
```
[dbx][2022-11-03 10:28:23.870] 🆗 Deployment file conf/deployment.yaml exists and will be used for deployment
[dbx][2022-11-03 10:28:23.873] Starting new deployment for environment prod
[dbx][2022-11-03 10:28:23.873] Using profile provided from the project file
[dbx][2022-11-03 10:28:23.874] Found auth config from provider EnvironmentVariableConfigProvider, verifying it
[dbx][2022-11-03 10:28:23.875] Found auth config from provider EnvironmentVariableConfigProvider, verification successful
[dbx][2022-11-03 10:28:24.801] The following path will be used for the jinja loader: /builds/doubleverify/measurement/data-platform/playground/dv-spark-python/conf with file deployment.yaml
[dbx][2022-11-03 10:28:24.816] No build logic defined in the deployment file. Default pip-based build logic will be used.
[dbx][2022-11-03 10:28:24.817] Workflows ['apps-daily-dbx-7-etl'] were selected for further operations
[dbx][2022-11-03 10:28:24.818] Following the provided build logic
[dbx][2022-11-03 10:28:24.818] 🐍 Building a Python-based project
[dbx][2022-11-03 10:28:26.002] ✅ Python-based project build finished
[dbx][2022-11-03 10:28:26.003] Locating package file
[dbx][2022-11-03 10:28:26.004] Package file located in: dist/dv_spark_python-0.0.1-py3-none-any.whl
[dbx][2022-11-03 10:28:26.281] Starting the traversal process
[dbx][2022-11-03 10:28:26.282] Processing libraries for task apps-daily-dbx-7-etl
[dbx][2022-11-03 10:28:26.283] ✅ Processing libraries for task apps-daily-dbx-7-etl - done
[dbx][2022-11-03 10:28:26.284] ⬆ Uploading local file dv_spark_python/jobs/apps_daily/etl_job.py
[dbx][2022-11-03 10:28:26.970] ✅ Uploading local file dv_spark_python/jobs/apps_daily/etl_job.py
[dbx][2022-11-03 10:28:26.971] ⬆ Uploading local file dist/dv_spark_python-0.0.1-py3-none-any.whl
[dbx][2022-11-03 10:28:27.536] ✅ Uploading local file dist/dv_spark_python-0.0.1-py3-none-any.whl
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.10/site-packages/dbx/commands/deploy.py:157 in deploy │
│                                                                              │
│   154 │   │   │   │   wf_manager = WorkflowDeploymentManager(api_client, ele │
│   155 │   │   │   │   wf_manager.apply()                                     │
│   156 │   │   else:                                                          │
│ ❱ 157 │   │   │   adjuster.traverse(deployable_workflows)                    │
│   158 │   │   │   if not _assets_only:                                       │
│   159 │   │   │   │   wf_manager = WorkflowDeploymentManager(api_client, dep │
│   160 │   │   │   │   wf_manager.apply()                                     │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:186 in  │
│ traverse                                                                     │
│                                                                              │
│   183 │   │   dbx_echo("Starting the traversal process")                     │
│   184 │   │   self.property_adjuster.library_traverse(workflows, self.additi │
│   185 │   │   self.property_adjuster.file_traverse(workflows, self.file_adju │
│ ❱ 186 │   │   self.property_adjuster.property_traverse(workflows)            │
│   187 │   │   self.property_adjuster.cluster_policy_traverse(workflows)      │
│   188 │   │   dbx_echo("Traversal process finished, all provided references  │
│   189                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:106 in  │
│ property_traverse                                                            │
│                                                                              │
│   103 │   │   :param workflows:                                              │
│   104 │   │   :return: None                                                  │
│   105 │   │   """                                                            │
│ ❱ 106 │   │   for element, parent, index in self.traverse(workflows):        │
│   107 │   │   │                                                              │
│   108 │   │   │   if isinstance(element, V2dot0Workflow):                    │
│   109 │   │   │   │   # legacy named conversion                              │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:53 in   │
│ traverse                                                                     │
│                                                                              │
│    50 │   │   elif isinstance(_object, list):                                │
│    51 │   │   │   for idx, sub_item in enumerate(_object):                   │
│    52 │   │   │   │   yield sub_item, _object, idx                           │
│ ❱  53 │   │   │   │   for _out in self.traverse(sub_item, _object, idx):     │
│    54 │   │   │   │   │   yield _out                                         │
│    55 │   │                                                                  │
│    56 │   │   # process any other kind of nested references                  │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:61 in   │
│ traverse                                                                     │
│                                                                              │
│    58 │   │   │   for key, sub_element in _object.__dict__.items():          │
│    59 │   │   │   │   if sub_element is not None:                            │
│    60 │   │   │   │   │   yield sub_element, _object, key                    │
│ ❱  61 │   │   │   │   │   for _out in self.traverse(sub_element, _object, ke │
│    62 │   │   │   │   │   │   yield _out                                     │
│    63 │   │   else:                                                          │
│    64 │   │   │   # yield the low-level objects                              │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:46 in   │
│ traverse                                                                     │
│                                                                              │
│    43 │   │   if isinstance(_object, dict):                                  │
│    44 │   │   │   for key, item in _object.items():                          │
│    45 │   │   │   │   yield item, _object, key                               │
│ ❱  46 │   │   │   │   for _out in self.traverse(item, _object, index_in_pare │
│    47 │   │   │   │   │   yield _out                                         │
│    48 │   │                                                                  │
│    49 │   │   # if element is a list, simply continue traversing             │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:53 in   │
│ traverse                                                                     │
│                                                                              │
│    50 │   │   elif isinstance(_object, list):                                │
│    51 │   │   │   for idx, sub_item in enumerate(_object):                   │
│    52 │   │   │   │   yield sub_item, _object, idx                           │
│ ❱  53 │   │   │   │   for _out in self.traverse(sub_item, _object, idx):     │
│    54 │   │   │   │   │   yield _out                                         │
│    55 │   │                                                                  │
│    56 │   │   # process any other kind of nested references                  │
│                                                                              │
│ /usr/local/lib/python3.10/site-packages/dbx/api/adjuster/adjuster.py:44 in   │
│ traverse                                                                     │
│                                                                              │
│    41 │   │                                                                  │
│    42 │   │   # if element is a dictionary, simply continue traversing       │
│    43 │   │   if isinstance(_object, dict):                                  │
│ ❱  44 │   │   │   for key, item in _object.items():                          │
│    45 │   │   │   │   yield item, _object, key                               │
│    46 │   │   │   │   for _out in self.traverse(item, _object, index_in_pare │
│    47 │   │   │   │   │   yield _out                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: dictionary changed size during iteration
```

## Context
I've migrated to 0.8.2 and got this error from dbx api, any chance you need to do a shallow copy to the dict when iterating over it?
## Your Environment

* dbx version used: 0.8.2
* Databricks Runtime version:

**Comment by renardeinside** [comment]
hi @aviadshimoni , 
could you please share the contents of conf/deployment.yml? I would like to repro the issue

**Comment by aviadshimoni** [comment]
@renardeinside thanks for the quick response
```
etl-cluster-props: &etl-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"
    spark_conf:
      #      spark.databricks.delta.preview.enabled: 'true' #todo check if needed
      spark.sql.shuffle.partitions: 'auto'
      spark.databricks.adaptive.autoOptimizeShuffle.enabled: 'true'
    driver_instance_pool_id: "instance-pool://n1-standart-32*60"
    instance_pool_id: "instance-pool://n1-standart-32*60"
    runtime_engine: STANDARD
    gcp_attributes:
      google_service_account: "databrick-general-prod@gp-ms-gbl-databricks.iam.gserviceaccount.com"
      zone_id: auto

  etl-cluster: &etl-cluster
    new_cluster:
      <<: *etl-cluster-props
      autoscale:
        min_workers: 5
        max_workers: 15
      policy_id: cluster-policy://general-purpose-cluster-policy

environments:
  prod:
    workflows:
      - name: "apps-daily-dbx-7-etl"
        schedule:
          quartz_cron_expression: "0 0 1 * * ?"
          timezone_id: "America/New_York"
          pause_status: "PAUSED"
        tags:
          owner: "data-platform-team"
          description: "apps-daily-with-dbx-7"
        permissions:
          access_control_list:
            - user_name: "service-principal://data-platform"
              permission_level: "IS_OWNER"
            - group_name: "data-platform"
              permission_level: "CanManageRun"
        tasks:
          - task_key: "apps-daily-dbx-7-etl"
            <<: *etl-cluster
            max_retries: 2
            min_retry_interval_millis: 300000
            retry_on_timeout: false
            timeout_seconds: 9000
            libraries:
              - maven:
                  coordinates: "com.vertica.spark:vertica-spark:3.3.2"
            spark_python_task:
                python_file: "file://dv_spark_python/jobs/apps_daily/etl_job.py"

 
```
