### ISSUE TITLE
[bug] multiple workflows only showing one

### ISSUE THREAD

**Issue by justinTM** [databrickslabs/dbx#567]
## Expected Behavior
want to define multiple elements in the list named "workflows" in deployment file.

## Current Behavior
getting error that dbx can't find any workflows by the name

```console
Exception: 
[1426]  Workflow reset-all was requested, but not provided in deployment
[1427]   file.
[1428]  Available workflows are: 
[1429] ['my-org-name-project-name']
```

## Steps to Reproduce (for bugs)
1. define a deployment file:
    ```yaml
    # deployment.yaml.j2
    ... other stuff omitted ...

      workflows: &workflows
        - name: my-org-name-project-name
          <<:
            - *permissions-common
          <<:
            - *notifications-common
          <<:
            - *schedule-common
          tags:
            <<: *global-tags
          tasks:
            - ...
        - name: reset-all
          <<:
            - *permissions-common
          <<:
            - *notifications-common
          <<:
            - *schedule-common
          tags:
            <<: *global-tags
          ...

    environments:
      # environment names must correspond to .gitlab-ci.yml variable CI_ENVIRONMENT_STAGES
      dev:
        workflows:
          - <<: *workflows
      prod:
        workflows:
          - <<: *workflows
    ```

2. deploy via dbx
    ```shell
    export JOB_NAME=reset-all
    dbx deploy --deployment-file "$FILEPATH_FINAL_JOB_DEFINITION" --job "$JOB_NAME" "${DBX_ARGS_ARRAY[@]}"
    ```

i also loaded up the dbx API to see if the underlying data was missing:
1.  use our ci/cd script which adds environment variables from `.env` files to `spark_env_vars` key
    ```python
    # write_dbx_deployment_file.py
    from dbx.api.config_reader import ConfigReader
    from pathlib import Path
    import os
    import json
    import re
    from dotenv import dotenv_values


    # this script will:
    #   1. render the job definition yaml template
    #   2. replace references to environment variables with their values

    # Load DBX env vars directly
    prefix = "DBX"

    CI_PROJECT_DIR = os.environ["CI_PROJECT_DIR"]
    FILEPATH_OUT = os.environ["FILEPATH_FINAL_JOB_DEFINITION"]
    FILEPATH_IN = Path(os.environ["FILEPATH_DEPLOYMENT_YML"])
    FILEPATH_DOT_ENV = os.path.join(CI_PROJECT_DIR, ".env")
    STAGE = os.environ["CI_ENVIRONMENT_STAGE"]
    DIR_PARAMS = os.path.join(CI_PROJECT_DIR, "parameters")

    # read job definition yaml file
    config_reader = ConfigReader(FILEPATH_IN)
    deployment = config_reader.get_environment(STAGE)

    # make spark_env_vars key from env vars in parameters/<stage>.env file
    filepath_params = os.path.join(DIR_PARAMS, f"{STAGE}.env")

    # override generic .env file with parameters/<environment>.env file
    vars_dict = dotenv_values(FILEPATH_DOT_ENV)
    vars_dict.update(dotenv_values(filepath_params))

    pattern = re.compile(r'{prefix}\w+'.format(prefix=prefix))
    ENV_VARS = {key: val for key, val in os.environ.items() if pattern.match(key)}
    vars_dict.update(ENV_VARS)

    # multi-task
    if deployment:
        for i, flow in enumerate(deployment.payload.workflows):
            for cluster in flow["job_clusters"]:
                cluster["new_cluster"]["spark_env_vars"].update(vars_dict)
    ```
2.
    ```python
    >>> len(deployment.payload.workflows)
    1
    ```

## Your Environment
```console
$ databricks --version
Version 0.17.3
$ dbx --version
[dbx][2022-11-08 11:36:27.801] 🧱Databricks eXtensions aka dbx, version ~> 0.7.6
```

**Comment by justinTM** [comment]
i think the `--job $JOB_NAME` in dbx deploy command may be contributing to this behavior? not sure

**Comment by renardeinside** [comment]
hi @justinTM , 
yes - when you specify the job name this list gets stripped to a single workflow. This is expected behaviour. 
Are you using `dbx` APIs or the CLI interface?

**Comment by justinTM** [comment]
hey Ivan, thanks for the fast reply. i fixed it :) 

change this:
```yaml
environments:
  # environment names must correspond to .gitlab-ci.yml variable CI_ENVIRONMENT_STAGES
  dev:
    workflows:
      - <<: *workflows
  prod:
    workflows:
      - <<: *workflows
```

to this:
```yaml
# deployment.yaml.j2
environments:
  dev:
    workflows: *workflows
  prod:
    workflows: *workflows
```

yaml anchors are something i'm still learning!
