### ISSUE TITLE
DBX tries to execute build activities even if no_build: true

### ISSUE THREAD

**Issue by dhamgithub** [databrickslabs/dbx#577]
Expected Behaviour
----
DBX should skip build activities when deploying notebook only workflows.

Current Behaviour
----
Build activities are attempted according to the console output after running dbx deploy --no-package, even if no_build: true is specified in the deployment.yaml file.
...
> dbx deploy --no-package
...
[dbx][2022-11-13 23:59:10.877] Profile DEFAULT will be used for deployment
[dbx][2022-11-13 23:59:12.248] All available workflows were selected for further operations: ['dbx-demo-job']
[dbx][2022-11-13 23:59:12.265] No build actions will be performed.
[dbx][2022-11-13 23:59:12.278] 🐍 Building a Python-based project
⠏ Building the package 🔨[dbx][2022-11-13 23:59:14.807]
💥Command execution failed
...

Steps to Reproduce (for bugs)
----
1. Run: dbx init
2. Write new conf/deployment.yaml:
```
build:
    no_build: true
  environments:
    default:
      workflows:
        - name: "dbx-demo-job"
          tasks:
            - task_key: "task1"
              new_cluster:
                spark_version: "11.3.x-scala2.12"
                node_type_id: "Standard_DS3_v2"
                num_workers: 1
              deployment_config:
                no_package: true
              notebook_task:
                notebook_path: "/My folder/My notebook"
```
3. Run: dbx deploy --no-package

Context
----
Attempting to use DBX to set up Notebook only workflows.

Observed in code that build activities proceed even if no_build is specified: https://github.com/databrickslabs/dbx/blob/main/dbx/models/build.py#L24-L52

Your Environment
----
dbx version used: 0.8.6
Databricks Runtime version: 11.3.x-scala2.12
