### ISSUE TITLE
Variables on UNIX for assets-only  launch --parameters

### ISSUE THREAD

**Issue by goldstein0101** [databrickslabs/dbx#606]
Hey, so i have a workflow with three tasks and each task has 5 parameters, now it would be a really huge and redundent effort to write all possible parameters each time, instead i could use for loop inside bash script and assign those variables inside --parameters.
Problem is that --paramterers are json dict where keys must be in double qoutes, and then whole --parameters string must begin inside single quotes, and in UNIX system, single quotes are used for literals, so u cannot do anything inside them(pass variables).
Is there a way for me to pass variables like that?

```bash
    for arg in "$ARGS[@]}"
    do
       dbx launch ... --parameters='[{"task_key": "key", "parameters": [ "--arg1", "${arg}"]}]'
    done
fi
```
This is just short example, i have 3 tasks with 10 different arguments values.So i would have to rewrite it 10 times for each task.

**Comment by renardeinside** [comment]
If you have many parameters I would recommend creating a single file and passing it to the tasks, e.g.:

```yml
# conf/properties.dev.yml

task1: 
  param1: some
  param-group1: 
    listParam: ["a", "b", "c"]
    elementParam: ["a", "b", "c"]

task2: 
  param1: some-other
  param-group1: 
    listParam: ["a", "b", "c"]
    elementParam: ["a", "b", "c"]
```

Then parse this file across various tasks and provide the relevant payload to relevant task. 
For prod, use a different file:

```yml
# conf/properties.prod.yml

task1: 
  param1: "PROD1_PARAM_VALUE"
  param-group1: 
    listParam: ["a", "b", "c"]
    elementParam: ["a", "b", "c"]

task2: 
  param1: "PROD2_PARAM_VALUE"
  param-group1: 
    listParam: ["a", "b", "c"]
    elementParam: ["a", "b", "c"]
```

When you need an execute or deploy in assets mode, pass the `conf/properties.dev.yml` as parameters, when you need prod deployment- pass prod etc.
