### ISSUE TITLE
dbx execute fails on python_wheel_task

### ISSUE THREAD

**Issue by pspeter** [databrickslabs/dbx#607]
## Current Behavior

```bash
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\venv\lib\site-packages\dbx\commands\execute.py:136 in execute                                 │
│                                                                                                  │
│   133 │   │   upload_via_context=upload_via_context,                                             │
│   134 │   │   pip_install_extras=pip_install_extras,                                             │
│   135 │   )                                                                                      │
│ ❱  68 │   │   │   if self._task.python_wheel_task.named_parameters:                              │
│    69 │   │   │   │   self.preprocess_task_parameters(self._task.python_wheel_task.named_param   │
│    70 │   │   │   elif self._task.python_wheel_task.parameters:                                  │
│    71 │   │   │   │   self.preprocess_task_parameters(self._task.python_wheel_task.parameters)   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'dict' object has no attribute 'named_parameters'

```

## Steps to Reproduce (for bugs)

Specify a simple task in deployment.yml:

```yaml
environments:
  default:
    strict_path_adjustment_policy: true
    workflows:
      - name: "workflow-foo"
        python_wheel_task:
          package_name: "package"
          entry_point: "entrypoint"
          parameters: [ "a", "b" ] 
```

Run dbx execute:

`dbx execute --cluster-name "cluster-xyz" --job "workflow-foo"`

## Context

Same error pops up if you specify named_parameters instead of parameters.

## Your Environment

* dbx version used: 0.8.0 - 0.8.7 are all affected
* Databricks Runtime version: 11.2
* Windows 10, python 3.9

**Comment by renardeinside** [comment]
the Jobs API 2.0 doesn't support python_named_task. You'll need to use the following:
```
environments:
  default:
    workflows:
      - name: "workflow-foo"
        python_wheel_task:
          tasks:
            - task_key: "some-key"
                  package_name: "package"
                  entry_point: "entrypoint"
                  parameters: [ "a", "b" ] 
```
