### ISSUE TITLE
dbx launch reports missing package instalation but dbx execute works well

### ISSUE THREAD

**Issue by jfecunha** [databrickslabs/dbx#650]
## Context

I'm running a **spark_python_task** through **dbx**. I use poetry to generate the package wheel.
The deployment file is the following:

```
build:
  commands:
    - "poetry build -f wheel" 

environments:
  dev:
    workflows:
      ####################################################
      # Need to have the package installed on the cluster
      ####################################################
      - name: "testing"
        existing_cluster_id: "cluster_id"
        spark_python_task:
          python_file: "file://python.py"
```

I can run the code through `dbx execute` like:
```
dbx execute testing --cluster-name="cluster_name" --deployment-file=./.dbx/deploy.yaml --environment=dev
```
It works as expected. However, when I deploy the workflow and launch the workflow on a job run I have an error mentioning that the package installed via wheel is not installed.

```
dbx deploy testing --deployment-file=./.dbx/deploy.yaml --environment=dev
```

```
dbx launch testing  --environment=dev 
```
Why **dbx execute** work and **dbx launch** don't? Is there something that I'm missing?
Would anyone be able to help me with this? Thanks

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: 10.4
