### ISSUE TITLE
Question: secrets with jinja templating enabled

### ISSUE THREAD

**Issue by MartinRoth** [databrickslabs/dbx#672]
## Expected Behavior

I would like to use jinja templating and variables defined in a databricks backed secret scope. 

This code works without jinja templating (derived from https://dbx.readthedocs.io/en/latest/reference/deployment/#configuring-complex-deployments)
```
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-scala2.12"
    node_type_id: "Standard_DS3_v2"
    spark_env_vars:
      PYPI_TOKEN: "{{secrets/pypi/token}}"
```

## Current Behavior

If I enable jinja-support I get:

```
UndefinedError: 'secrets' is undefined
```

I see that the definition of the secrets overlaps with the environment variables, but so far I couldn't figure out, how to change the definition of the secret.

## Your Environment

* dbx version used: 0.8.4
* Databricks Runtime version: 0.17.4
