### ISSUE TITLE
Init script for cluster

### ISSUE THREAD

**Issue by ptaban** [databrickslabs/dbx#686]
Hey, is there a way to pass path for init_script that is inside project, and not on static place on dbfs.
Since it will just convert file:// and file:fuse// to dbfs:/ and /dbfs/ while init script must start with file:.
If does not start with file:/ it will throw error:

Run result unavailable: job failed with error message
 Unexpected user error while creating the cluster for the job. Cause: INVALID_PARAMETER_VALUE: File init scripts (specified with a file:/ prefix) can only be specified for clusters with custom docker containers.

Configuration looks like this:

```
custom:
  cluster_props: &cluster_props
    spark_version: "11.3.x-cpu-ml-scala2.12"
    node_type_id: "m4.large"
    driver_node_id: "m4.large"
    creator_user_name: 
    policy_id: 
    init_scripts:
      file:
        destination: "file://conf/init_script.sh"
```
