### ISSUE TITLE
dbx creates a random directory everytime a deployment is done

### ISSUE THREAD

**Issue by guillesd** [databrickslabs/dbx#713]
## Expected Behavior
When running the CLI command
```bash
dbx deploy --environment dev --deployment-file some_deployment.yml
```
I would expect dbx to give me the option to overwrite the previous wheel, and/or use my tagging strategy (v0.0.0, v0.0.1) to define the directory for the artifacts. So for example, the following command should have the following output:
```bash
$ dbfs ls dbfs:/dbx/my_package/ --profile=my-company-profile
dbfs:/dbx/data-processing/v0.0.0
dbfs:/dbx/data-processing/v.0.0.1
dbfs:/dbx/data-processing/v.0.0.2
```
Ideally you could target also a specific version if you want to patch it, for example:
```bash
dbx deploy --environment dev --deployment-file some_deployment.yml --overwrite=v.0.0.2
```
This is just an idea, maybe we can come up with a better one. But the concept is to be able to **really** target a directory maybe with a specific tag. For the development flow I understand that this could generate conflicts (multiple branches doing multiple builds), but for production I really thing this is needed.

## Current Behavior
However, the actual behaviour is that the target directory (in this case `dbfs:/dbx/my_package`) has a random temporary directory added to it, which generates a random folder for each deployment I do. Deployments pile up and I know have (after 2 months of using dbx) 75 deployment folders in `dbfs`. Example output from the terminal:

```bash
$ dbfs ls dbfs:/dbx/my_package/ --profile=my-company-profile
dbfs:/dbx/data-processing/005d57e75e5b4482ab06f4432e0e88a3
dbfs:/dbx/data-processing/008e46b1e20c41e1a71abef4a1e03eeb
dbfs:/dbx/data-processing/00edb25776e449b993147091e9141083
dbfs:/dbx/data-processing/01680e91a3d94d8984507101b7c47b54
dbfs:/dbx/data-processing/01748315ff8d45aaa329023c5c940cbf
dbfs:/dbx/data-processing/01b7a8f8c5a849ba8b11f27db5d6332b
dbfs:/dbx/data-processing/0204220629074dea9e93bd4a371dcb2c
dbfs:/dbx/data-processing/0205884a8a5d41398da369fe0f36a180
dbfs:/dbx/data-processing/0229c6d4e9514fb9842277342e264003
dbfs:/dbx/data-processing/024fcd1c0927448696874f1da2059d36
dbfs:/dbx/data-processing/0290719a883649a5937e50e56e524684
dbfs:/dbx/data-processing/02a19db5f0e4489eba821d37ac3e8f80
dbfs:/dbx/data-processing/02cd06767f754d90804cbe8824ea2a2e
dbfs:/dbx/data-processing/0399c325efe84ea1b26fc4be62d2b676
dbfs:/dbx/data-processing/04dcb462cabc44e988a2977878096ba5
dbfs:/dbx/data-processing/05031e6ab8ba47e39c6beb7efb51d002
dbfs:/dbx/data-processing/0513488f4e6f42cda2fbd2094a71dc77
dbfs:/dbx/data-processing/05b0c31098e4461198a03134bd0efeda
dbfs:/dbx/data-processing/05d0a2f0fe2842899872a7b5519ceebe
dbfs:/dbx/data-processing/070eb98f68a54f6091f9e74c6b2b54c7
dbfs:/dbx/data-processing/072d5aee274f4c08a155086beb7a11a5
...
```

## Steps to Reproduce (for bugs)
```
The `some_deployment.yml` file looks like:
```yaml
  dev:
    workflows:
      - name: "some_workflow"
        job_clusters:
          - job_cluster_key: some_cluster
            new_cluster:
              <<: *common-cluster-definition
              autoscale:
                min_workers: 2
                max_workers: 4
        tasks: 
          - task_key: some_task
            python_wheel_task:
              package_name: my_package
              entry_point: script
            job_cluster_key: some_cluster
            timeout_seconds: 0
```

The `project.json` looks like:
```json
{
    "environments": {
        "dev": {
            "profile": "my-company-profile",
            "storage_type": "mlflow",
            "properties": {
                "workspace_directory": "/Shared/dbx/projects/my_package",
                "artifact_location": "dbfs:/dbx/my_package"
            }
        }
    },
    "inplace_jinja_support": false,
    "failsafe_cluster_reuse_with_assets": false,
    "context_based_upload_for_execute": false
}
```
And run the following command:
```bash
dbx deploy --environment dev --deployment-file some_deployment.yml
```

## Context
It is really confusing to have a random folder being created with each deployment. This also means that 3 workflows pointing to the same wheel can be pointing to the same version of this wheel but three different builds in three different folders. Moreover, you cannot really clean up the dbfs path without checking what paths are your active workflows pointing too.

## Your Environment

* dbx version used: 0.8.7
* Databricks Runtime version: 11.3 LTS

## Hint for implementation
[This function](https://github.com/databrickslabs/dbx/blob/8dc436d7d1f9604583735f13f2fb2bf94ff5e8f0/dbx/api/context.py#L157) called by the [ContextBasedUploader)[https://github.com/databrickslabs/dbx/blob/8dc436d7d1f9604583735f13f2fb2bf94ff5e8f0/dbx/utils/file_uploader.py#L80] creates the temporary directory using `tempfile. mkdtemp()`. Depending on a flag in the CLI or a config block in the deployment.yml, we could specify to use the version (or any other tag) in the directory name (including branch name as a posibility). What do you think?
