### ISSUE TITLE
Issue Running Photon Cluster with DBX

### ISSUE THREAD

**Issue by sam-h-bean** [databrickslabs/dbx#782]
## Expected Behavior
Job runs with photon

## Current Behavior
I get 
```bash
Run result unavailable: run failed with error message
 Unexpected user error while preparing the cluster for the job. Cause: BAD_REQUEST: INVALID_PARAMETER_VALUE: Invalid spark version 11.3.x-photon-scala2.12.
```

## Steps to Reproduce (for bugs)
I have a config for the cluster that looks like 
```yaml
photon-cluster: &photon-cluster
  new_cluster:
    spark_version: "11.3.x-photon-scala2.12"
    node_type_id: "Standard_DS3_v2"
    runtime_engine: PHOTON
    autoscale:
      min_workers: 2
      max_workers: 7
```

## Context
I want to run photon

## Your Environment

* dbx version used: 0.8.14
* Databricks Runtime version: 11.3.x LTS

**Comment by renardeinside** [comment]
hi @sam-h-bean , 
You're using a wrong `spark_version` string, it should look like this:

```yaml
photon-cluster: &photon-cluster
  new_cluster:
    spark_version: "11.3.x-scala2.12"
    node_type_id: "Standard_DS3_v2"
    runtime_engine: PHOTON
    autoscale:
      min_workers: 2
      max_workers: 7
``` 

When in doubt, use the Databricks UI - start creating a cluster, set it up via UI and then click JSON - it will show you the proper configuration.
