### ISSUE TITLE
Management of SQL queries, alerts, dashboards and warehouses

### ISSUE THREAD

**Issue by dome4** [databrickslabs/dbx#786]
## Expected Behavior

Currently it is already possible to reference SQL assets in jobs via the `sql_task`. For this, the ids of the assets are resolved via the [adjuster](https://github.com/databrickslabs/dbx/blob/941743b6d58f0053863eb76711a65b9952524189/dbx/api/adjuster/adjuster.py#L101). This is implemented by replacing the placeholders `warehouse://`, `query://`, `dashboard://` and `alert://.` However, in order to make the SQL assets completely deployable alongside the workflows and ensure that the assets are present when the workflows are created, they also need to be created, updated and deleted. Therefore, in my opinion, it would make sense to include additional properties in the `deployment.yml` file in addition to the current `workflows` property.

An example deployment.yml could look like this:

```
...
environments:
 dev:
   workflows:
      ...

   warehouses:
      - name: "sql-warehouse"
        cluster_size: "Small"
        min_num_clusters: 1
        max_num_clusters: 2
        auto_stop_mins: 10
        enable_serverless_compute: "true"
        warehouse_type: "PRO"
        channel:
          name: "CHANNEL_NAME_CURRENT"

   queries:
      - name: "sql-query"
        query: "SELECT * FROM data"
        parent: "folder:///Shared/deployments/dev/queries"
...
```

To achieve the desired behavior, API services must be created for each SQL asset (queries, alerts, dashboards and warehouses) based on the [NamedPipelinesService](https://github.com/databrickslabs/dbx/blob/main/dbx/api/services/pipelines.py) or [NamedJobsService](https://github.com/databrickslabs/dbx/blob/main/dbx/api/services/jobs.py). The Databricks REST API provides all the necessary endpoints for managing SQL assets.

Are there currently any considerations for the management of SQL assets with dbx? Should they be stored as separate files like notebooks or does it make sense to define the SQL assets in the deployment.yml?
