### ISSUE TITLE
Named parameters not working as expected

### ISSUE THREAD

**Issue by zerodarkzone** [databrickslabs/dbx#803]
## Expected Behavior
When using named parameters in the deployment file, these should be reflected in the databricks job.

ej: deployment
```
python_wheel_task:
  <<: *python_wheel_task
  named_parameters:
    pipeline: intermediate
    env: dev
    conf-source: file:fuse://conf
    runner: ThreadRunner
```

## Current Behavior
With the given parameters configuration. I get this in Databricks.

![image](https://github.com/databrickslabs/dbx/assets/22160983/5395ead0-ac75-42c2-afb3-2db23f0601af)

An extra parameter called "named_parameters" is added to the task.
This is a problem for the task im running.

## Steps to Reproduce (for bugs)
Deploy a python wheel task using named parameters.

## Your Environment

* dbx version used: 0.8.15
* Databricks Runtime version: 12.2 LTS
