### ISSUE TITLE
Wheel file based job deployment not removing previous wheel version from cluster

### ISSUE THREAD

**Issue by tarique-msci** [databrickslabs/dbx#834]
I have a PySpark job that I am deploying as wheel package using dbx on Databricks. The deployment file looks something like below:
```
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "12.2.x-scala2.12" 
    node_type_id: "Standard_D4ds_v5"
    spark_conf:  # remove if not needed
      spark.databricks.delta.preview.enabled: 'true'
      # For postgres connection
      spark.network.timeout: '300000'
    # instance_pool_id: "instance-pool://some-pool-name" # remove if not needed
    # driver_instance_pool_id: "instance-pool://some-pool-name"  # remove if not needed
    runtime_engine: PHOTON
    # init_scripts:  # remove if not needed
    #   - dbfs:
    #       destination: dbfs:/<enter your path>

  basic-auto-scale-props: &basic-auto-scale-props
    autoscale:
      min_workers: 2
      max_workers: 4

  basic-static-cluster: &basic-static-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 2

environments:
  default:
    workflows:
      - name: "test-pipeline"
        job_clusters:
          - job_cluster_key: "basic-cluster"
            <<: *basic-static-cluster
          - job_cluster_key: "basic-autoscale-cluster"
            <<: *basic-autoscale-cluster
        tasks:
          - task_key: "spark-etl"
            job_cluster_key: "basic-cluster"
            python_wheel_task:
              package_name: "dbx_test"
              entry_point: "main"
```
I have configured a job cluster for the actual job run but during development I use an all purpose cluster. To do the same I go to the Workflows UI on Databricks and swap out the cluster. For the first run this works fine. But if I modify the code, redeploy, swap the cluster and run it again, it installs the new wheel file on the cluster without removing the earlier one. And it run the older implementation instead of new one with changes. To run the new one I have to uninstall the wheel file from the cluster manually, restart the cluster and then only it works. 

Example screenshot of libraries installed in cluster.

![image](https://github.com/databrickslabs/dbx/assets/109334753/e6e292f9-373a-4e95-880b-aae0017a71ef)

## Expected Behavior
When a new version of the job in deployed and launched on a cluster the older wheel should be uninstalled.
## Current Behavior
The new version of the wheel package is installed on the cluster without removing the older version and the run refers to the old wheel package.

## Steps to Reproduce (for bugs)

- Create a wheel based spark job
- Deploy to Databricks using dbx
- Swap the cluster to an all purpose cluster and run
- Make changes to the code, build wheel and re-deploy using databricks
- Swap to the same cluster and run it again

After this you will have multiple version of the same wheel package installed on the cluster.

## Your Environment

* dbx version used: 0.8.18
* Databricks Runtime version: 12.2 LTS
