### ISSUE TITLE
Job Notifications

### ISSUE THREAD

**Issue by IamSandeepGunda** [databrickslabs/dbx#838]
### Discussed in https://github.com/databrickslabs/dbx/discussions/831

<div type='discussions-op-text'>

<sup>Originally posted by **IamSandeepGunda** August  8, 2023</sup>
We've been exploring the [Databricks Notification Destinations](https://docs.databricks.com/en/administration-guide/workspace/settings/notification-destinations.html) and set up a Slack destination to notify on errors and when the job is over it's runtime thresholds. 

Is there a way to set these up in the `deployment.yml`? 

Currently, if I set it up on the UI, it's wiped away next time i perform a `dbx deploy...` to that job.</div>

**Comment by stephen-bowser** [comment]
Yep, I've managed this. Grab the ID of your slack endpoint and put it in the config of your workflow:

```
        webhook_notifications:
          on_failure:
            - id: "xxx"
          on_success:
            - id: "xxx"
```
