### ISSUE TITLE
## How to parameterized DBX Python Notebook

### ISSUE THREAD

**Issue by ssr8998** [databrickslabs/dbx#841]
The overall goal is to make database name (prod/dev/test) dynamic for each notebook in dbx job and passing that database name directly from jenkins without modifying notebook file or deployment.yaml file for each environment .
If I am creating a dbx job where I have few databricks notebook and I want to pass the database name dynamically into each python notebook without using databricks widget (assuming I am using sys.args that will read the input of dbx clie parameter and I want to run my job something like :- 
dbx launch --job "my_job_name" --parameter='{"db_name": "my_db_name"}' and it will send that info to my job and all associated notebook which will read these info from conf/deployment.yaml and in deployment.yaml file I will have something like :--
notebook_task:
       notebook_path:"/Reposs/My_github_repo/blala/notebookname"
       base_parameters:
               db_name"{{env.db_name_from_env}}"
## Your Environment

* dbx version used:0.7.4
* databricks-cli:0.17.3
* spark_version:12.2.x-scala2.12
* Databricks Runtime version: 12.2 LTS or above

**Comment by doug-cresswell** [comment]
It is probably better practice to deploy separate workflows for separate environments, but to answer your question you can use the jinja support functionality ([Jinja Support](https://dbx.readthedocs.io/en/latest/features/jinja_support/?h=jinja)) combined with environment variables.

Also see [Passing Parameters](https://dbx.readthedocs.io/en/latest/guides/general/passing_parameters/?h=param)

Your deployment file should look something like this:
conf/deployment.yml.j2

```yaml
build:
  python: "pip"

environments:
  default:
    workflows:
      - name: "my-workflow"
        tasks:
          - task_key: "task1"
            python_wheel_task:
              package_name: "some-pkg"
              entry_point: "some-ep"
              parameters: ["database_name", "{{ env['DATABASE_NAME'] }}"]
```

Deploy via CLI
```bash
export DATABASE_NAME=dev
dbx deploy -e dev --deployment-file conf/deployment.yml.j2 "my-workflow"
```

Launch via CLI
```bash
dbx launch -e dev --parameters='{"python_params":["database_name","${DATABASE_NAME}"]}' "my-workflow"
```

Note that you will need to append the `.j2` extension to your yaml file, or alternately enable in place jinja support in your project configuration.
